### ISSUE TITLE
Inclusion in setup.py generated QuotedString error 

### ISSUE THREAD

**Issue by timtautges** [RaubCamaioni/CythonPEG#1]
Inserted the code as recommended to setup.py. The resulting error was:

> ERROR: Command errored out with exit status 1:
>    command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/ttautges/d3d/855-pyi/opt/extern/moab/pymoab/setup.py'"'"'; __file__='"'"'.../setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-098t2wa9
>        cwd: .../
>   Complete output (7 lines):
>   Traceback (most recent call last):
>     File "<string>", line 1, in <module>
>     File ".../setup.py", line 12, in <module>
>       from pymoab import cython_peg as cpeg
>     File ".../pymoab/cython_peg.py", line 75, in <module>
>       STRING = QuotedString(quoteChar="'", unquote_results=False) | QuotedString(quoteChar='"', unquote_results=False)
>   TypeError: QuotedString.__init__() got an unexpected keyword argument 'unquote_results'
>   ----------------------------------------
> WARNING: Discarding file://.... Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Note, I removed the specific path and substituted '...'.

**Comment by RaubCamaioni** [comment]
This is a pyparsing version error.  Pyparsing needs to be >= 3.1.0.

**Comment by RaubCamaioni** [comment]
Changed to python package, dependencies auto installed.
